version: '3'

services:
  backend:
    build: ./backend
    container_name: myapp_backend
    ports:
      - "5001:5001"
  frontend:
    build: ./frontend
    container_name: myapp_frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  
    